### PR TITLE
Wider support for promise based UIImagePickerController display

### PR DESCRIPTION
**Pull request by kdubb**
Adds an override to ```promiseViewController``` that returns the entire media information dictionary from the image picker.

This is essential for applications that require picking videos as well or that might need asset meta-data.

### CODE REVIEW

**Comment by mxcl** [comment]
There is no need to duplicate `UIImagePickerControllerProxy` to `UIImagePickerControllerInfoProxy` just use `UIImagePickerControllerProxy`.

**Comment by kdubb** [comment]
Good catch... no idea what I had done there.  Fixed.

**Comment by kdubb** [comment]
Status?

**Comment by mxcl** [comment]
Please merge @nathanhosselton

**Comment by nathanhosselton** [comment]
Again, sorry this was never merged. Can you resubmit the PR for the master branch?

**Comment by kdubb** [comment]
Rebased. Not sure why Github decided to show the entire history to rebase my 2 commits.

**Comment by nathanhosselton** [comment]
Your commits are now merged into master. This PR still targeted `changes-for-3.0` so I had to perform the merge locally then push and GitHub isn't smart enough to detect so I'm closing the PR manually.

**Pull request closed without merging**
