### PR TITLE
Make podspec of v3.0.0 lint

### PR DESCRIPTION
**Pull request by svenmuennich**
The commits contained in this PR are all done to make the podspec lint again. For now this is not a 100% solution, because I had to disable the `Bolts` category. Here's some more info about each commit:

* [d6d694e](https://github.com/mxcl/PromiseKit/commit/d6d694e6e60c42e61d93dd0112ad300cfaf1c532): The MessageUI subspec was searching at `Categories/MessageUI`, while the files were located at `Categories/MessagesUI`. I renamed the directory to `MessageUI` and fixed the Xcode project too. The `Bolts` extension Swift file could not be found in the workspace so I removed it and added it again.
* [4e9c22a](https://github.com/mxcl/PromiseKit/commit/4e9c22a38e7c0c5bff5a8f8ff2ebce7ded579841): `NSURLConnection`'s `sendAsynchronousRequest:queue:completionHandler:` is deprecated in iOS 9.0 and OS X 10.11, hence I replaced it with the suggested `dataTaskWithRequest:completionHandler:` of `NSURLSession`. I'm not sure whether this is a 100% fix, because after all the fixed category is on `NSURLConnection`.
* [79d68d0](https://github.com/mxcl/PromiseKit/commit/79d68d0de711e4ed919f50c819fc35040e288de1): The podspec had [this long part](https://github.com/mxcl/PromiseKit/blob/53e058b30124e1b8d1455801f451b0da56e15b2f/PromiseKit.podspec#L144-L217) marked as `deprecated`. I looked it up and found that it has been there since the release of `v2.0.0` earlier this year, so I think it's fine to remove it for `v3.0.0`.
* [259a70a](https://github.com/mxcl/PromiseKit/commit/259a70a6a12d02e3e82c960f997b3fbe7a228caa): Although I fixed the file reference to the `Bolts` extension in [d6d694e](https://github.com/mxcl/PromiseKit/commit/d6d694e6e60c42e61d93dd0112ad300cfaf1c532) I could not make it compile. It looks like although it's supposed to support Objective-C, the umbrella header is missing. To make the podspec lint, I had to disable the respective subspec for now. Here's the linter error for the `Bolts` subspec (`pod lib lint --verbose --subspec=PromiseKit/Bolts --fail-fast`):
```
    - ERROR | [iOS] [PromiseKit/Bolts]  /.../PromiseKit.build/module.modulemap:2:19: error: umbrella header 'Umbrella.h' not found
    - NOTE  | [iOS] [PromiseKit/Bolts]  <unknown>:0: error: could not build Objective-C module 'PromiseKit'
```
* [34b2f53](https://github.com/mxcl/PromiseKit/commit/34b2f53f716ea1fb51bb3955039bebd33b83a4dd): The main problem of the podspec was the support of watchOS. The linter failed, because most of the subspecs require frameworks that are not available on watchOS. This was caused by setting the `s.watchos.deployment_target = '2.0'` in the root spec, which is then inherited by all subspecs. To fix this, I added separate `deployment_targets` to those subspecs that are only available on iOS and/or OS X.

As I wrote before, this is not yet a 100% solution. Feedback and of course a fix for the `Bolts` subspec are welcome.

### CODE REVIEW

**Comment by nathanhosselton** [comment]
Hey again. Thank you once more for all of your efforts here. It is greatly appreciated. I'm currently working out how to match this up with some of the work already performed that I haven't pushed yet as there is some overlap and also some differences. But I wanted to go ahead and leave a comment so you know it isn't being ignored. I'll do my best to merge as much of your work as possible.

**Comment by mxcl** [comment]
Great work, but indeed, we shouldn’t modify the `NSURLConnection` like that. So lets remove that, and if COcoaPods won't lint that we can `--ignore-warnings` as I'm not sure what other solution there is.

**Comment by svenmuennich** [comment]
Okay, shall I revert the commit on this branch or will you just pick the stuff you like to keep and push it directly?

**Comment by nathanhosselton** [comment]
@svenmuennich In the interest of time I have pushed to CocoaPods with what I had working today. I sincerely apologize that I did not end up using any of the work you submitted in this PR. But PromiseKit is working at this moment thanks in part to your efforts. I hope this won't be a deterrent for you to continue contributing in the future as your work was of excellent quality. Please stick around. I'm sure there will be more work to do very soon. And I have proven unable to keep up with it alone.

**Comment by svenmuennich** [comment]
Don't worry about it. The most important thing is that it works now :+1:

**Pull request closed without merging**
