### PR TITLE
port non-2xx response handling over from objc

### PR DESCRIPTION
**Pull request by allen-zeng**
Currently ```NSURLConnection``` in Swift lib fulfills server non 200 responses.

This change ports the Objective-C functionality to reject non 200 responses over. Starting from [this line](https://github.com/mxcl/PromiseKit/blob/master/objc/NSURLConnection+PromiseKit.m#L86)

### CODE REVIEW

**Comment by mxcl** [comment]
Thanks, I wonder why I didn't do this already.

FFR, the diff on line 44 shouldn’t have made it into the PR.

**Comment by allen-zeng** [comment]
No thank _you_ for all the awesome work! :)

Interesting point on line 44, is it because that it isn't related to the pull request or is it because there is a specific coding style that you'd like to see?

**Comment by mxcl** [comment]
The diff just changes formatting and thus isn't related to the content of your PR.

If you wanted to change the formatting it should be a separate PR.

Consequently the diff for this commit contains unrelated modifications and impedes the legibility of the actual fix.

**Comment by allen-zeng** [comment]
:+1:

**Pull request merged**
