### PR TITLE
Add EventKit request access promise

### PR DESCRIPTION
**Pull request by lammertw**
This pull request adds a public function EKEventStoreRequestAccess to get access to EventKit to add events to the user's calendar. Example usage:

    func addEvent() {
        EKEventStoreRequestAccess().then { eventStore in
            let event = EKEvent(eventStore: eventStore)
            event.calendar = eventStore.defaultCalendarForNewEvents
            event.title = "My event"

            let editEventController = EKEventEditViewController(nibName: nil, bundle: nil)

            editEventController.event = event
            editEventController.eventStore = eventStore
            
            self.presentViewController(editEventController, animated: true, completion: nil)
        }
    }

### CODE REVIEW

**Comment by nathanhosselton** [comment]
Thanks for this! I see that you posted in the gitter chat about getting this under testing. Let's see if we can get that working before merging.

**Comment by lammertw** [comment]
I managed to run the test with the fix in #373 and added a test. Hopefully this can be approved and merged now.

**Comment by nathanhosselton** [comment]
This looks good! Again, so, so sorry for the month+ delay on this. Do you mind rebasing onto the current HEAD of master and resolving the conflict? It's just the new Bolts framework reference. Keep the new reference and delete the old one (line 89 in the project.pbxproj file). Then this can be merged.

**Comment by nathanhosselton** [comment]
Went ahead and rebased on my end. GitHub did not detect. Closing manually.

**Pull request closed without merging**
