### PR TITLE
Tap on queue

### PR DESCRIPTION
**Pull request by Igor-Palaguta**

### CODE REVIEW

**Comment by mxcl** [comment]
The failing test is my fault.

**Comment by mxcl** [comment]
Many thanks 👍🏻

**Comment by Igor-Palaguta** [comment]
Thank you for PromiseKit!

**Comment by Igor-Palaguta** [comment]
@mxcl Can't find this commit in master anymore

**Comment by mxcl** [comment]
Sorry, restored.

**Comment by Igor-Palaguta** [comment]
thanks

**Pull request merged**
