### PR TITLE
WIP. Update for Xcode 8 Beta 6

### PR DESCRIPTION
**Pull request by uny**
Build succeeded, but tests are failing.

### CODE REVIEW

**Comment by raphaelcruzeiro** [comment]
Did you get this to build on Beta 6 @uny ? I'm getting 2 errors here:

```
PromiseKit/Sources/AnyPromise.swift:305:19: Ambiguous use of 'subscript'
PromiseKit/Sources/URLDataPromise.swift:90:58: 'URLRequest' is inaccessible due to 'private' protection level
```

Seems that on Beta 6, extensions can no longer access private members of the classes they extend.

**Comment by gmckenzi** [comment]
Yeah, @raphaelcruzeiro -- just change the declarations of URLRequest and URLResponse from private to fileprivate.

**Comment by mxcl** [comment]
Tests will fail since Travis doesn't support beta4. However I have been working on this patch.

**Comment by mxcl** [comment]
My attempt has test failures, so I tried this locally and it has ~20 failures too.

Mostly in AnyPromise stuff.

**Comment by mxcl** [comment]
In fact my bad: Travis has been updated to beta 6.

**Comment by mxcl** [comment]
Pushed to swift-3.0 and the 4.0.0 tag was updated.

**Comment by uny** [comment]
Thank you!

**Pull request closed without merging**
