### PR TITLE
PromiseKit/Swift works on iOS 7.1

### PR DESCRIPTION
**Pull request by gfx**
I use PromiseKit/Swift for an application targeted to iOS 7.1. It works fine expect for its deployment target, iOS 8.0.

Can you downgrade the deployment target? Or is there any reason to use 8.0?

### CODE REVIEW

**Comment by mxcl** [comment]
This was because it is marked as an embedded framework and they only support iOS 8. So I hope there won't be further issues since I have merged this.

**Comment by pgherveou** [comment]
I get a warning now when compiling, is this related?

```
Ld /Users/pg/Library/Developer/Xcode/DerivedData/Jogabo-fhrfmmlapzdgnseyyatthkyulkde/Build/Products/Debug-iphonesimulator/PromiseKit.framework/PromiseKit normal x86_64
    cd /Users/pg/Jogabo/app-v2/ios-app/PromiseKit/swift
    export IPHONEOS_DEPLOYMENT_TARGET=7.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -L/Users/pg/Library/Developer/Xcode/DerivedData/Jogabo-fhrfmmlapzdgnseyyatthkyulkde/Build/Products/Debug-iphonesimulator -F/Users/pg/Library/Developer/Xcode/DerivedData/Jogabo-fhrfmmlapzdgnseyyatthkyulkde/Build/Products/Debug-iphonesimulator -filelist /Users/pg/Library/Developer/Xcode/DerivedData/Jogabo-fhrfmmlapzdgnseyyatthkyulkde/Build/Intermediates/PromiseKit.build/Debug-iphonesimulator/PromiseKit.build/Objects-normal/x86_64/PromiseKit.LinkFileList -install_name @rpath/PromiseKit.framework/PromiseKit -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -objc_abi_version -Xlinker 2 -fapplication-extension -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -force_load -Xlinker /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a -Xlinker -add_ast_path -Xlinker /Users/pg/Library/Developer/Xcode/DerivedData/Jogabo-fhrfmmlapzdgnseyyatthkyulkde/Build/Intermediates/PromiseKit.build/Debug-iphonesimulator/PromiseKit.build/Objects-normal/x86_64/PromiseKit.swiftmodule -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=7.1 -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/pg/Library/Developer/Xcode/DerivedData/Jogabo-fhrfmmlapzdgnseyyatthkyulkde/Build/Intermediates/PromiseKit.build/Debug-iphonesimulator/PromiseKit.build/Objects-normal/x86_64/PromiseKit_dependency_info.dat -o /Users/pg/Library/Developer/Xcode/DerivedData/Jogabo-fhrfmmlapzdgnseyyatthkyulkde/Build/Products/Debug-iphonesimulator/PromiseKit.framework/PromiseKit

ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
```

**Comment by mxcl** [comment]
Yes. So either everyone gets a warning, or people must change the targeted SDK. Hmm.

**Comment by pgherveou** [comment]
that sucks :(

**Comment by mxcl** [comment]
You can fix it by setting the deployment target to 8.0. But I don't feel this is ideal. I need to ponder it.

**Comment by pgherveou** [comment]
my deployment target is set to 8.0 but I still get the warning...

On Mon, Feb 2, 2015 at 7:16 PM, Max Howell <notifications@github.com> wrote:

> You can fix it by setting the deployment target to 8.0. But I don't feel
> this is ideal. I need to ponder it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mxcl/PromiseKit/pull/132#issuecomment-72585491>.
>



-- 
--
PG

**Comment by pgherveou** [comment]
Can you set a variable in the deployment target field so it use the projects value?

**Comment by mxcl** [comment]
@pgherveou not that I know of, but we'd use it if it exists.

**Pull request merged**
