### PR TITLE
Fixed mistake with barrier on serial queue

### PR DESCRIPTION
**Pull request by djmixroman**

### CODE REVIEW

**Comment by mxcl** [comment]
Seems like we should make the q concurrent instead, the only other use is a “read” operation.

**Comment by djmixroman** [comment]
> Seems like we should make the queue concurrent instead, the only other use is a “read” operation.

Are u want to use concurrent queue.sync with barrier?

**Comment by mxcl** [comment]
The queue should be iniatlized concurrent.

**Comment by mxcl** [comment]
QoS utility seems wrong, this is often a user-initiated situation, where scrolling will trigger the need for an image to download. I would just leave it as `default` since there are many various situations where the QoS could be different, even where eg. you are pre-loading the images so you go with `utility` but then the user scrolls that cell into view and now you need it with `userInitiated` but this caching system has no way to upgrade the existing fetch to be a higher QoS.

**Pull request merged**
