### PR TITLE
Update PromiseKit.podspec

### PR DESCRIPTION
**Pull request by pmusolino**
Fixed Xcode warning relative to this https://github.com/mxcl/PromiseKit/issues/928#issuecomment-424960602

### CODE REVIEW

**Comment by mxcl** [comment]
I deliberately removed this. Cocoapods is broken. They have tickets open for a true fix where I can specify the range of Swift versions I support. If I don’t remove this we don’t sctuslly support all versions with Cocoapods and are lying.

**Comment by mxcl** [comment]
That thread has a fix you can apply in your pod file. But even better stop using Cocoapods it’s a pos. Or open a ticket and tell them to fix their bullshit.

**Comment by mxcl** [comment]
Like there is no reason whatsoever that Cocoapods doesn’t generate a project with this flag cleared so xcode doesn’t prompt you to upgrade the dependencies swift version. They are just lazy developers who have made a terrible piece of software.

**Comment by mxcl** [comment]
Notably Alamofire also does not set this for the same reasons. Setting it to 4 was mostly acceptable IMO, but setting it to 4.2 to fix this warning would limit PMK a lot, so I just removed it instead, since the warning would be there for everyone on Xcode 10 anyway.

I updated our documentation to provide the “fix” and am watching the ticket to add version ranges to CocoaPods and may even step up and do the damn work.

**Comment by pmusolino** [comment]
Thanks @mxcl for clarifying the situation.

**Comment by mxcl** [comment]
Update: I decided to try and add the feature myself, so followed the “getting started for contributors” guide for CocoaPods, the provide a script to setup the environment, it took 40 minutes to run (wtf?) and failed. So fuck that shit. CocoaPods is awful.

**Pull request closed without merging**
