### PR TITLE
Enabled the skip install option, was causing app archive builds to work poorly.

### PR DESCRIPTION
**Pull request by joshorr**

### CODE REVIEW

**Comment by mxcl** [comment]
Did you meant to close this?

**Comment by joshorr** [comment]
I wanted to merge it to our own master (though a review process) before I would merge request it to you. I selected the wrong repo is all.  I'll send another PR shortly.

**Comment by joshorr** [comment]
(if your interested?)

**Comment by mxcl** [comment]
Definitely. Thanks.

**Pull request closed without merging**
