### PR TITLE
Add ability to change the default dispatch queue for all promises

### PR DESCRIPTION
**Pull request by programmerdave**
This PR allows you to change the default dispatch queue for all promises in Swift and in ObjC.

It fixes: #280 and allows you to use Zalgo in unit tests so that you don't have to depend on dispatch_async so you can get fast deterministic tests (http://martinfowler.com/articles/nonDeterminism.html)

### CODE REVIEW

**Comment by mxcl** [comment]
I like it.

1. I think there should be just one function, do it in objc so it is accessible from both
2. I think it should be named `PMKDefaultDispatchQueue()` since that is more consistent with other such things in PromiseKit.

**Comment by programmerdave** [comment]
@mxcl I changed the name, made it accessible from both, and all tests pass (aside from an existing Issue which I submitted a separate PR for). Thanks!

**Comment by nathanhosselton** [comment]
Looks good to me.

**Comment by mxcl** [comment]
LGTM! Many thanks.

**Comment by programmerdave** [comment]
No problem! Thanks! Do you know when this would be merged into master?

**Comment by nathanhosselton** [comment]
Tomorrow morning if not tonight!

**Comment by nathanhosselton** [comment]
Squashed and merged. Closing manually.

Thanks again, @programmerdave!

**Pull request closed without merging**
