### PR TITLE
Fix #1332

### LINKED ISSUE #1332: Privacy Manifest
Hello, 

At WWDC23 Apple announced that apps and SDKs that make use of certain "required reason" APIs etc will need to provide a privacy manifest.
Does PromiseKit need to include this manifest?
Is this update on the roadmap for the team? I appreciate that enforcement won't happen until Spring 2024 but I wanted to make contact so that we can plan our own app releases to take this into account.

Here’s some useful references:

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

https://developer.apple.com/videos/play/wwdc2023/10060/

Thanks

### PR DESCRIPTION
**Pull request by RomanPodymov**
Hello.
Thank you for PromiseKit.
Fix #1332.

### CODE REVIEW

**Comment by mxcl** [comment]
Is this ready?

**Comment by RomanPodymov** [comment]
> Is this ready?

Hello @mxcl 
Not yet, SPM is failing. Or maybe I can fix SPM later.

**Comment by RomanPodymov** [comment]
> Is this ready?

Now it's ready.

**Comment by jayeshkawli** [comment]
@RomanPodymov Thank you for the fix. Much appreciated. Can we also make a release so that we can update our dependencies?

**Comment by RomanPodymov** [comment]
Hello @jayeshkawli 
Can you reproduce the issue using `master` branch? Currently I don't have any project with PromiseKit that I can upload to TestFlight.

**Comment by jayeshkawli** [comment]
> Hello @jayeshkawli Can you reproduce the issue using `master` branch? Currently I don't have any project with PromiseKit that I can upload to TestFlight.

I am not sure what you mean, can you please elaborate? To my original question, I meant making a next release like from this page https://github.com/mxcl/PromiseKit/releases so that we can fetch this change through SPM/Cocoapods. Or I can also do that if I have necessary permissions.

**Pull request merged**
