### PR TITLE
Set Compatibility version and Current version to 1

### PR DESCRIPTION
**Pull request by victorg1991**
I'm trying to distribute a binary which has this library as a dependency. I develop it using carthage

When I try to set up a project with my library using cocoapods and try to run it in the simulator it shows: Library version: XXX requires version 4.1.8 or later, but PromiseKit provides version 1.0.0

This is because cocoapods don't set the compatibility version and the current version (they reverted that change https://github.com/CocoaPods/CocoaPods/issues/3940 https://github.com/CocoaPods/CocoaPods/issues/3903

The reason of this change is because this seems to be the recommended approach 

You can see more related in this issue too (https://github.com/CocoaPods/CocoaPods/issues/3903)

### CODE REVIEW

**Comment by mxcl** [comment]
We already changed this because of Carthage: https://github.com/mxcl/PromiseKit/issues/620

So, I worry about it.

**Comment by victorg1991** [comment]
Oh sorry, I made a mistake, which I wanted to do is revert that change and use the default value which is that most of the frameworks use (instead of the current version of the framework)

**Comment by mxcl** [comment]
I will aim to tag a release and pod today, but it may end up being tomorrow, pretty busy today.

**Comment by victorg1991** [comment]
No problem at all, thank you so much! 💯

**Comment by victorg1991** [comment]
Any updates? :)

**Comment by mxcl** [comment]
Live.

**Comment by victorg1991** [comment]
🎉

**Pull request merged**
