### PR TITLE
tvOS and watchOS Support for PMK 1.x 

### PR DESCRIPTION
**Pull request by mofirouz**
This PR references issue #311. 

- Add necessary pod configs
- Updated XCode project to 1.7.0

Github didn't let me create a PR which had the 1.6.0 tag as it's base so I had to select master. To compare, please follow this https://github.com/heroiclabs/PromiseKit/commit/315e2f84b0d14721dcd0768ebbc764534bf00ff3

### CODE REVIEW

**Comment by mxcl** [comment]
This merges master. So that's not what we want.

I guess it didn't occur to me that you can't PR onto a tag. We'll need to create a branch. We never intended not to, just when we split 1.x off we didn't need one at the time.

**Comment by mofirouz** [comment]
@mxcl As you said, you can't create a PR based off a tag, but you can still commit the code without a branch to a new tag - the catch is only the owners can do that (because you are pushing directly to a commit/tag not to a PR).

I personally vote that for the sake of clarity for potentially future PRs, we create a branch for 1.x branch?

**Comment by nathanhosselton** [comment]
Agreed on the new branch. Not sure what to call it though. `promisekit-1.x` would work fine, but it's purpose would not be self evident. Something like `promisekit-objc`? Open to suggestions before creation.

**Comment by nathanhosselton** [comment]
I think I like `1.x` more despite my own criticisms. Will go with that unless there's objections.

**Comment by mofirouz** [comment]
Thanks a lot @nathanhosselton - Let me know when I should rebase the code for easier merge for you guys.

**Comment by nathanhosselton** [comment]
The new branch is now available at [`legacy-1.x`](https://github.com/mxcl/PromiseKit/tree/legacy-1.x). Sorry for the delay.

**Comment by mofirouz** [comment]
I'm closing this in favor of a new PR that is based on the legacy-1.x branch.

**Pull request closed without merging**
