### PR TITLE
note that cancel doesn't trigger catch block

### PR DESCRIPTION
**Pull request by ConfusedVorlon**

### CODE REVIEW

**Comment by ConfusedVorlon** [comment]
sorry - realised I was targeting v7

**Comment by ConfusedVorlon** [comment]
6.15.3 is the same...

**Comment by mxcl** [comment]
This just repeats the same text from two paragraphs above.

**Comment by ConfusedVorlon** [comment]
I guess so - I was just trying emphasise it.

**Comment by mxcl** [comment]
I think emphasizing it is a good idea. So stick the `**important**` with the other paragraph?

**Pull request closed without merging**
