### PR TITLE
Alert controller cancellation

### PR DESCRIPTION
**Pull request by kdubb**
PMKAlertController "Cancel" style actions now cancel the promise (currently it's reversed).  It also makes the Error enum conform to CancellableErrorType as required.

### CODE REVIEW

**Comment by kdubb** [comment]
Status?

**Comment by mxcl** [comment]
Should have been merged October 2nd.

**Comment by kdubb** [comment]
The typo was fixed in another commit so cancel rejects the promise.  My PR also makes the Error a CancellableErrorType so that you can use the cancel button as a way to cancel the promise.  That doesn't appear in the latest version of the file.

**Comment by nathanhosselton** [comment]
Yes, this was my mistake. I apologize @kdubb, yours should have been the PR that I merged.

If you would like to resubmit the PR for the master branch without https://github.com/reTXT/PromiseKit/commit/19a5ffe851ae55fefbbdf83679cf1c5aa6cd2732 I will merge.

**Comment by kdubb** [comment]
Rebased.

**Comment by nathanhosselton** [comment]
Merged but, again, had to do it locally, so this PR does not reflect. Closing manually.

**Comment by nathanhosselton** [comment]
And thank you, @kdubb! Both for your efforts and your patience.

**Pull request closed without merging**
