### PR TITLE
Tests for data races

### PR DESCRIPTION
**Pull request by xenadu**
A somewhat reliable test for #181. When Zalgo isn't properly protected, the test crashes on every iteration I ran (with memory corruption). When Zalgo is properly mollified the test passes. 

Also included a version for `then()` just to cover the situation where a data race is inadvertently introduced later.

### CODE REVIEW

**Comment by mxcl** [comment]
Thanks, but I can't pull unless it is 100% reliable or Travis will be emailing me with false failure reports.

**Comment by xenadu** [comment]
@mxcl I would never open a PR with a test that has any chance of generating spurious test failures. 

The unreliability of this test is that it can *in theory* pass when it should have failed. Never the other way around... If there is a data race present there is a small chance that the data race occurs in just such a perfect way as to allow the test to pass. I tried to set the iteration and stress counts high enough to make sure that doesn't happen, but it depends on how the system allocates dispatch queues, the number of processors, and other factors outside of our control.

I don't think proving the absence of a race in this context is a computable problem.

**Comment by mxcl** [comment]
aah yes, I should have realized that. My bad.

**Comment by mxcl** [comment]
Well in theory we could mock and stub so we can force the various race conditions, and then prove they don't happen, but I've never tried to do such a thing before. Maybe it's not practical.

**Pull request merged**
