### PR TITLE
[ObjC] Fix error leak and add test case

### PR DESCRIPTION
**Pull request by HarrisHao**
Reference #827 #828

### CODE REVIEW

**Comment by mxcl** [comment]
Merging. The Linux failures are not our fault: https://github.com/kylef/swiftenv/issues/125

**Comment by mxcl** [comment]
I'll push a release.

**Comment by HarrisHao** [comment]
Well, thank you very much.

**Comment by mxcl** [comment]
Just waiting on the CI, which is waiting on:  kylef/swiftenv#125

**Pull request merged**
