### PR TITLE
Add ability to use custom queue for error #280 #405

### PR DESCRIPTION
**Pull request by yannickl**
Hi there,

I really need to choose the queue where the error runs because I provide a library that uses PromiseKit and I don't want update the `PMKDefaultDispatchQueue` for the entire project.

I think the `error(on: queue)` can be pertinent in some use cases.

Best,

Yannick

### CODE REVIEW

**Comment by mxcl** [comment]
You didn't say why you need this.

**Comment by yannickl** [comment]
Sorry, here is a link to an example (this is more explicit): https://github.com/yannickl/AwaitKit/blob/master/Sources/AwaitKit.swift#L46

My library uses your PromiseKit as promise implementation. As you can see I need to block the main thread with a semaphore. So if an error occurred, I need to notify the semaphore.

I could update the `PMKDefaultDispatchQueue` but if the user also modify it on his own side (with the main queue), it can alter my library behaviour and entered in a deadlock.

**Comment by mxcl** [comment]
K, this seems like a good enough use-case to me. There have been good enough uses in the past, the problem is Swift+Xcode has hated error having another parameter and has been busted because of it.

I suggest we roll this into PMK4 / Swift3, if you can wait that long? I guess not.

In the meantime I'm cool with an additional method like:

    errorOnQueue(…)

Ugly, but I really don't want to break compilation for Swift 2.x users (it breaks the parser, foo foo foo).

**Comment by yannickl** [comment]
Yes, of course, I would like to have this feature before the release of PMK4 to be able to release my library.

I'll send you a pull request for with `errorOnQueue()` method to not break the compilation for Swift 2.x users.

Thank you!

**Comment by yannickl** [comment]
I just updated the pull request. I hope it'll be ok for you.

**Comment by mxcl** [comment]
LGTM thanks!

**Pull request merged**
