### PR TITLE
visionOS

### LINKED ISSUE #1326: Add support of visionOS
The platform of the target `X` (visionOS 1.0) is not compatible with PromiseKit (8.1.1), which does not support visionOS.

### PR DESCRIPTION
**Pull request by RomanPodymov**
Hello.
Thank you for PromiseKit.
visionOS support.
Fix #1326.

### CODE REVIEW

**Comment by mxcl** [comment]
Nice job. Approved. We should drop Carthage officially probs. Does anyone use it?

**Comment by mxcl** [comment]
Undraft it when ready

**Comment by RomanPodymov** [comment]
Hello @mxcl 
Probably someone is still using PromiseKit + Carthage since PromiseKit is an old and popular library. But we can at least disable Carthage CI for now.

**Comment by RomanPodymov** [comment]
Hello @mxcl 
It's ready for review.

**Pull request merged**
